name: NPCTrader
version: 1.1.3
main: com.MatCat.NPCTrader.NPCTrader
website: http://www.matcatsmp.com/
description: Provides NPC Based Shop System
authors: [MatCat]
commands:
  npctrader:
    description: Main NPC Command, type for help.
    usage: /npctrader
  npc:
    description: Alias for Main NPC command type for help.
    usage: /npc